name: 'Geoffrey K. Liu, Guy That Writes Shit'
favicon: null
layout_spectrum: 0.85896
typography_spectrum: 1
title: 'Geoffrey K. Liu, Writer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120e0d'
    - '#6d776f'
    - '#ffffff'
    - '#bca65b'
    - '#045a7b'
  brandStrength: 0.1875
  lightness: 0.21713065030053258
  saturation: 0.45448328787460923
  rhythmicContrast: 0.5334317984525114
purpose: []
