name: 'Geoffrey K. Liu, Author'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85113
title: 'Geoffrey K. Liu, Author'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4d4844'
    - '#78736f'
    - '#d6cecb'
    - '#b3afae'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
